import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/hooks/ThemeProvider";
import { Toaster } from "sonner";


export const metadata: Metadata = {
  title: "Finance Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <Toaster richColors position="bottom-right"/>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem  disableTransitionOnChange>
          {children}
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
